name = "glyaea"
title = "glyaea"

[paths]
favicon = "https://cdn.jsdelivr.net/gh/twitter/twemoji/assets/svg/2728.svg"
posts = "posts"
site = "_site"
template = ["template.html", "template.css"]
url = "https://glyaea.github.io"
